//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _02.DateTimeService.Client.DateTimeServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DateTimeServiceReference.IServiceDatetime")]
    public interface IServiceDatetime {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDatetime/GetWeekDay", ReplyAction="http://tempuri.org/IServiceDatetime/GetWeekDayResponse")]
        string GetWeekDay(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDatetime/GetWeekDay", ReplyAction="http://tempuri.org/IServiceDatetime/GetWeekDayResponse")]
        System.Threading.Tasks.Task<string> GetWeekDayAsync(System.DateTime date);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceDatetimeChannel : _02.DateTimeService.Client.DateTimeServiceReference.IServiceDatetime, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceDatetimeClient : System.ServiceModel.ClientBase<_02.DateTimeService.Client.DateTimeServiceReference.IServiceDatetime>, _02.DateTimeService.Client.DateTimeServiceReference.IServiceDatetime {
        
        public ServiceDatetimeClient() {
        }
        
        public ServiceDatetimeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceDatetimeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDatetimeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDatetimeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetWeekDay(System.DateTime date) {
            return base.Channel.GetWeekDay(date);
        }
        
        public System.Threading.Tasks.Task<string> GetWeekDayAsync(System.DateTime date) {
            return base.Channel.GetWeekDayAsync(date);
        }
    }
}
